core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

djmenu/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from djmenu import settings

admin.site.site_header = 'Django Menu'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('products/', include('products.urls')),
    path('menu/', include('menu.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('new/', views.product_new, name='product_new'),
    path('list/', views.products_list, name='products-list'),
    path('list/two-flavors/', views.two_flavors, name='two-flavors'),
    path('categories/', views.categories_list, name="categories_list"),
    path('category/new/', views.category_new, name="category_new"),
    path('variations/', views.variations_list, name="variations_list"),
    path('variation/new/', views.variation_new, name="variation_new"),
    path('import/woo/<product_id>/',
         views.import_from_woocommerce,
         name="import_from_woocommerce"),
    path('import/woo/category/<category_id>/',
         views.import_all_from_woocommerce_category,
         name="import_all_from_woocommerce_category"),
]

products/models.py
from django.db import models

from core.models import TimeStampedModel, Active


class Category(TimeStampedModel, Active):
    name = models.CharField('Categoria', max_length=50, unique=True)
    description = models.TextField('Descrição', blank=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('name',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'


class Product(TimeStampedModel, Active):
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('name',)
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"


class Variation(TimeStampedModel, Active):
    name = models.CharField('Variação', max_length=50, unique=True)
    description = models.TextField('Descrição', blank=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'


class ProductVariation(TimeStampedModel, Active):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE, null=True)
    price = models.DecimalField('Preço', max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.product.name + ' - ' + self.variation.name + ' - ' + self.price.__str__())

    class Meta:
        ordering = ('product', 'variation', 'price')
        unique_together = [('product', 'variation')]

products/forms.py
from django.forms import ModelForm, TextInput, Textarea, NumberInput, Select

from .models import Product, Category, Variation, ProductVariation


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
            'description',
        ]

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'})
        }


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'price',
            'category',
        ]

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'price': NumberInput(attrs={'class': 'form-control'}),
            'category': Select(attrs={'class': 'form-control'}),
        }


class VariationForm(ModelForm):
    class Meta:
        model = Variation
        fields = [
            'name',
            'description',
        ]

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'})
        }


class ProductVariationForm(ModelForm):
    class Meta:
        model = ProductVariation
        fields = [
            'product',
            'variation',
            'price',
        ]

        widgets = {
            'product': Select(attrs={'class': 'form-control'}),
            'variation': Select(attrs={'class': 'form-control'}),
            'price': NumberInput(attrs={'class': 'form-control'}),
        }

products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Min
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.shortcuts import render, redirect

from .facade import get_product, get_from_category
from .forms import CategoryForm, ProductForm, VariationForm, \
    ProductVariationForm
from .models import ProductVariation, Category, Product, Variation


@login_required
def products_list(request):
    produtos = Product.objects.all().order_by('category__name', 'name')

    produtos_simples = produtos.filter(productvariation__isnull=True)

    variacoes = ProductVariation.objects.all()

    context = {
        'produtos_simples': produtos_simples,
        'variacoes': variacoes,
    }
    return render(request, 'products/list_products.html', context=context)


@login_required
def product_new(request):
    product_form = Product()
    variations_formset = inlineformset_factory(Product, ProductVariation,
                                               form=ProductVariationForm,
                                               extra=1)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product_form, prefix='main')
        formset = variations_formset(request.POST, instance=product_form,
                                     prefix='product')

        if form.is_valid() and formset.is_valid():
            novo_produto = form.save(commit=False)
            novo_produto.save()
            formset.save()
            messages.success(request, "Novo produto cadastrado.")
            return redirect(products_list)
    else:
        form = ProductForm(instance=product_form, prefix='main')
        formset = variations_formset(instance=product_form, prefix='product')

    return render(request, 'products/product_new.html', {'form': form,
                                                         'formset': formset})


def two_flavors(request):
    variacoes = ProductVariation.objects.all()
    min_price_broto = ProductVariation.objects.filter(
        variation__name='Broto').aggregate(Min('price'))
    min_price_grande = ProductVariation.objects.filter(
        variation__name='Grande').aggregate(Min('price'))
    context = {
        'variacoes': variacoes,
        'min_price_broto': min_price_broto['price__min'],
        'min_price_grande': min_price_grande['price__min']
    }
    return render(request, 'products/sliced.html', context=context)


@login_required
def categories_list(request):
    categories = Category.objects.all()
    context = {'categories': categories}

    return render(request, 'products/list_categories.html', context)


@login_required
def category_new(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Nova categoria cadastrada.")
            return redirect(categories_list)
    else:
        form = CategoryForm()

    return render(request, 'products/category_new.html', {'form': form})


@login_required
def variations_list(request):
    variacoes = Variation.objects.all()
    context = {'variacoes': variacoes}

    return render(request, 'products/list_variations.html', context)


@login_required
def variation_new(request):
    if request.method == "POST":
        form = VariationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Nova variação cadastrada.")
            return redirect(variations_list)
    else:
        form = VariationForm()

    return render(request, 'products/variation_new.html', {'form': form})


@login_required
def import_from_woocommerce(request, product_id):
    product = get_product(product_id=product_id)
    return JsonResponse(product.json())


@login_required
def import_all_from_woocommerce_category(request, category_id):
    products = get_from_category(category_id)
    return JsonResponse(products)

templates/products/category_new.html
{% extends "base.html" %}

{% block title %} Nova Categoria {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <div class="page-header">
    <h3 class="page-title">Categorias</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'categories_list' %}">Categorias</a></li>
        <li class="breadcrumb-item active" aria-current="page">nova</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% if form.errors %}
      <div class="col-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {% for erro in form.errors %}
            {{ erro }}
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form action="." method="post">
            {% csrf_token %}

            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="id_name">Nome</label>
                {{ form.name }}
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="id_description">Descrição</label>
                {{ form.description }}
              </div>
            </div>

            <div class="row my-5">
              <div class="col-md-12" style="display: flex; justify-content: space-between;">
                <input type="submit" value="Salvar" class="btn btn-success">
              </div>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/products/list_categories.html
{% extends "base.html" %}

{% block title %} Page Blank {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
  <style>
    .food-menu-item {
      border-bottom-style: dotted;
      border-color: gray;
    }

    .food-category-title {
      border-bottom-style: dotted;
      border-color: gray;
    }
  </style>
{% endblock stylesheets %}

{% block content %}
  <div class="page-header">
    <h3 class="page-title">Categorias</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="mdi mdi-home menu-icon"></i></a></li>
        <li class="breadcrumb-item active" aria-current="page">categorias</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <p class="card-description"> Listando todas as <code>categorias</code>
          </p>
          {% for category in categories %}
            <div class="row justify-content-between align-items-center food-menu-item">
              <div class='col-lg-9'>
                <h2 class='mt-2'>{{ category.name }}</h2>
              </div>
              <div class="col-lg-3 flex-row d-flex">
                <div class="col"></div>
                <div class='col'>
                  {% if category.product_set.count <= 1 %}
                    <a class="btn btn-primary my-4" href="#" role="button">
                      {{ category.product_set.count }} item
                    </a>
                  {% else %}
                    <a class="btn btn-primary my-4" href="#" role="button">
                      {{ category.product_set.count }} itens
                    </a>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/products/list_products.html
{% extends "base.html" %}

{% block title %} Produtos {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
  <style>
    .food-menu-item {
      border-bottom-style: dotted;
      border-color: gray;
    }

    .food-category-title {
      border-bottom-style: dotted;
      border-color: gray;
    }
  </style>
{% endblock stylesheets %}

{% block content %}
  <div class="page-header">
    <h3 class="page-title">Produtos</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="mdi mdi-home menu-icon"></i></a></li>
        <li class="breadcrumb-item active" aria-current="page">produtos</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <p class="card-description"> Listando todos os produtos <code>simples</code>
          </p>
          {% for product in produtos_simples %}
            <div class="row justify-content-between align-items-center food-menu-item">
              <div class='col-lg-7'>
                <h2 class='mt-2'>{{ product.name }}</h2>
              </div>
              <div class="col-lg-5 flex-row d-flex">
                <div class="col"></div>
                <div class='col'>
                  <a class="btn btn-primary my-4" href="#" role="button">R$ {{ product.price }}</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <p class="card-description"> Listando todos os produtos <code>variáveis</code></p>
          {% regroup variacoes by product as variacoes_list %}
          {% for variacao in variacoes_list %}
            <div class="row justify-content-between align-items-center food-menu-item">
              <div class='col-lg-7'>
                <h2 class='mt-2'>{{ variacao.grouper }}</h2>
                <p>{{ variacao.grouper.description }}</p>
              </div>
              <div class="col-lg-5 flex-row d-flex">
                {% for variacao in variacao.list %}
                  <div class='col'>
                    <a class="btn btn-primary my-4" href="#" role="button">{{ variacao.variation }}:<br>
                      R$ {{ variacao.price }}</a>
                  </div>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/products/list_variations.html
{% extends "base.html" %}

{% block title %} Page Blank {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
  <style>
    .food-menu-item {
      border-bottom-style: dotted;
      border-color: gray;
    }

    .food-category-title {
      border-bottom-style: dotted;
      border-color: gray;
    }
  </style>
{% endblock stylesheets %}

{% block content %}

  <div class="page-header">
    <h3 class="page-title">Variações</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="mdi mdi-home menu-icon"></i></a></li>
        <li class="breadcrumb-item active" aria-current="page">variações</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <p class="card-description"> Listando todas as <code>variações</code>
          </p>
          {% for variacao in variacoes %}
            <div class="row justify-content-between align-items-center food-menu-item">
              <div class='col-lg-9'>
                <h2 class='mt-2'>{{ variacao.name }}</h2>
                <p>{{ variacao.description }}</p>
              </div>
              <div class="col-lg-3 flex-row d-flex">
                <div class="col"></div>
                <div class='col'>
                  {% if variacao.productvariation_set.count <= 1 %}
                    <a class="btn btn-primary my-4" href="#" role="button">
                      {{ variacao.productvariation_set.count }} item
                    </a>
                  {% else %}
                    <a class="btn btn-primary my-4" href="#" role="button">
                      {{ variacao.productvariation_set.count }} itens
                    </a>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/products/product_new.html
{% extends "base.html" %}

{% block title %} Novo Produto {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  <script>
      $(document).ready(function () {
          $("#add-item").click(function (ev) {
              ev.preventDefault();
              let count = $('#variacoes').children().length;
              let tmplMarkup = $("#variacao-produto").html();
              let compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
              $("div#variacoes").append(compiledTmpl);

              // update form count
              $('#id_product-TOTAL_FORMS').attr('value', count + 1);

          });
      });
  </script>

  <div class="page-header">
    <h3 class="page-title">Produtos</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'products-list' %}">Produtos</a></li>
        <li class="breadcrumb-item active" aria-current="page">novo</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% if form.errors %}
      <div class="col-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {% for erro in form.errors %}
            {{ erro }}
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    {% endif %}

    {% if formset.errors %}
      <div class="col-12">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {% for erro in formset.errors %}
            {{ erro }}
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form action="." method="post">
            {% csrf_token %}

            <div class="form-row">
              <div class="form-group col-md-7">
                <label for="id_name">Nome</label>
                {{ form.name }}
              </div>
              <div class="form-group col-md-3">
                <label for="id_category">Categoria</label>
                {{ form.category }}
              </div>
              <div class="form-group col-md-2">
                <label for="id_price">Preço</label>
                {{ form.price }}
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="id_description">Descrição</label>
                {{ form.description }}
              </div>
            </div>

            {{ formset.management_form }}
            <div class="content" id="variacoes">
              {% for variation in formset %}
                <div id="item-{{ forloop.counter0 }}" class="row form-row spacer">
                  <div class="input-group">
                    <div class="col-md-9">
                      <label>Variação</label><br> {{ variation.variation }}
                    </div>
                    <div class="col-md-2">
                      <label>Preço</label><br> {{ variation.price }}</div>
                    <div class="col-md-1" style="margin-top: 38px;">{{ variation.DELETE }}
                      <label><i class="fas fa-trash"></i></label></div>
                  </div>
                </div>
              {% endfor %}
            </div>

            <div class="row my-5">
              <div class="col-md-12" style="display: flex; justify-content: space-between;">
                <button type="button" id="add-item" class="btn btn-primary">
                  <i class="fa fa-plus"></i> Add variação
                </button>
                <input type="submit" value="Salvar" class="btn btn-success">
              </div>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script type="text/html" id="variacao-produto">
    <div id="item-__prefix__" style="margin-top: 10px" class="row form-row spacer">
      <div class="input-group">
        <div class="col-md-9"><label>Variação</label><br> {{ formset.empty_form.variation }}</div>
        <div class="col-md-2"><label>Preço</label><br> {{ formset.empty_form.price }}</div>
        <div class="col-md-1" style="margin-top: 38px;">{{ formset.empty_form.DELETE }}
          <i class="fas fa-trash"></i></div>
      </div>
    </div>
  </script>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/products/variation_new.html
{% extends "base.html" %}

{% block title %} Nova Variação {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="page-header">
    <h3 class="page-title">Variações</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'variations_list' %}">Variações</a></li>
        <li class="breadcrumb-item active" aria-current="page">nova</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    {% if messages %}
      {% for message in messages %}
        <div class="col-12">
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% if form.errors %}
      <div class="col-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {% for erro in form.errors %}
            {{ erro }}
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form action="." method="post">
            {% csrf_token %}

            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="id_name">Nome</label>
                {{ form.name }}
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="id_description">Descrição</label>
                {{ form.description }}
              </div>
            </div>

            <div class="row my-5">
              <div class="col-md-12" style="display: flex; justify-content: space-between;">
                <input type="submit" value="Salvar" class="btn btn-success">
              </div>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}